# Generated by Django 5.0.7 on 2024-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('cost', models.FloatField()),
                ('images', models.ImageField(upload_to='./Food/images/')),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
