# Generated by Django 5.0.7 on 2024-09-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='login',
            name='images',
        ),
    ]
