# Generated by Django 5.0.7 on 2024-09-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_login_loginform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodiee',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='foodimages',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='updated',
        ),
    ]
