# Generated by Django 5.0.7 on 2024-09-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_foodiee_updated_remove_foodimages_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='category',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginform',
            old_name='name',
            new_name='username',
        ),
    ]
