# Generated by Django 5.0.7 on 2024-09-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
    ]
